// Code generated by go-validate tool. DO NOT EDIT.
package models

type ValidationError struct {
	Field string
	Error error
}

// Validate validates fields of User struct.
func (u User) Validate() ([]ValidationError, error) {
	var errors []ValidationError

	// ID; string; len(36)

	// Age; int; min(18); max(50)

	// Email; string; regexp(^\\w+@\\w+\\.\\w+$)

	// Role; UserRole; in(admin,stuff)

	return errors, nil
}

// Validate validates fields of App struct.
func (a App) Validate() ([]ValidationError, error) {
	var errors []ValidationError

	// Version; string; len(5)

	return errors, nil
}

// Validate validates fields of Response struct.
func (r Response) Validate() ([]ValidationError, error) {
	var errors []ValidationError

	// Code; int; in(200,404,500)

	// Body; string

	return errors, nil
}
