// Code generated by go-validate tool. DO NOT EDIT.
package models

func (u User) Validate() ([]ValidationError, error) {
	return nil, nil
}

func (a App) Validate() ([]ValidationError, error) {
	return nil, nil
}

func (r Response) Validate() ([]ValidationError, error) {
	return nil, nil
}
